@startmindmap
skinparam DefaultTextAlignment right

<style>
mindmapDiagram {
  .yachid {
    BackgroundColor lightgreen
  }
  .tzibur {
    BackgroundColor #FFBBCC
  }
}
</style>
left side
* קרבנות
** עולה
***:**עולת יחיד**
* מכפר על עוון עשה
* מכפר על לאו הניתק לעשה
* מכפר על הרהורי עברה; <<yachid>>
*** עולת צבור <<tzibur>>
** חטאת
*** חטאת חיצונית
**** חטאת יחיד <<yachid>>
***** **חטאת יחיד** <<yachid>>
***** **מטאת עולה ויורד** <<yachid>>
***** **חטאת עבודה זרה** <<yachid>>
***** **חטאת שעיר נשיא** <<yachid>>
***** **חטאת נזיר שנטמא** <<yachid>>
***** **חטאת זב** <<yachid>>
***** **חטאת זבה** <<yachid>>
***** **חטאת יולדת** <<yachid>>
***** **חטאת מצורע** <<yachid>>
**** חטאת צבור <<tzibur>>
***** **שעיר מוסף** <<tzibur>>
***** **חטאת הקרבה עם שתי הלחם** <<tzibur>>
*** חטאת פנימית
**** **פר כהן גדול** <<yachid>>
**** **שעיר לה׳** <<tzibur>>
**** **פר העלם** <<tzibur>>
**** **שעיר עבודה זרה** <<tzibur>>
**** **פר כהן משיח** <<tzibur>>
** אשם
** שלמים
** בכור
** מעשר
** פסח
@endmindmap